const InitialState = {
    darkMode: false,
    fifteen: { size: 4 },
    mosaic: { imgName: 'ff7remake', img: '/assets/mosaic/ff7remake.jpg', rows: 5, cols: 10 },
    wordle: { difficulty: 1 },
    tetris: { },
    mastermind: { difficulty: 0 },
    tyles: { level: 0, scores: Array.apply(0, { length: 120 }).map(() => { return { bestScore: 0, isBest: false } }) },
    minesweeper: { difficulty: 1, sectionsState: [true, false, true, false] },
    talks: { selectedTalk: 0 },
    simon: { level: 8, reverseMode: false },
    rpg: {
        plotStep: 'NewGame',
        party: [
            {
                name: 'Rainer',
                class: 0,
                lvl: 1,
                xp: 10,
                hp: 30,
                maxhp: 35,
                str: 20,
                agl: 5,
                int: 1,
                vit: 10,
                lck: 5,
                hit: 5,
                mdef: 15,
                equip: [],
            },
            {
                name: 'Galthier',
                class: 1,
                lvl: 1,
                xp: 7,
                hp: 30,
                maxhp: 30,
                str: 5,
                agl: 10,
                int: 5,
                vit: 5,
                lck: 15,
                hit: 5,
                mdef: 15,
                equip: [],
            },
            {
                name: 'Tia',
                class: 3,
                lvl: 1,
                xp: 27,
                hp: 28,
                maxhp: 28,
                str: 5,
                agl: 5,
                int: 15,
                vit: 10,
                lck: 5,
                hit: 5,
                mdef: 20,
                equip: [],
            },
            {
                name: 'Katt',
                class: 5,
                lvl: 1,
                xp: 0,
                hp: 10,
                maxhp: 20,
                str: 10,
                agl: 10,
                int: 10,
                vit: 5,
                lck: 5,
                hit: 7,
                mdef: 20,
                equip: [],
            },
        ],
        gold: 1000,
        inventory: [],
    }

};

export default InitialState;